// <auto-generated />
using System;
using Ambev.DeveloperEvaluation.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambev.DeveloperEvaluation.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20241015130000_AddUserTimestamps")]
    partial class AddUserTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("SaleNumber").IsRequired().HasColumnType("integer");
                    b.Property<DateTime>("SaleDate").IsRequired().HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CustomerId").IsRequired().HasColumnType("uuid");
                    b.Property<string>("CustomerName").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<Guid>("BranchId").IsRequired().HasColumnType("uuid");
                    b.Property<string>("BranchName").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<decimal>("TotalAmount").HasColumnType("numeric(18,2)");
                    b.Property<bool>("IsCancelled").IsRequired().HasColumnType("boolean");
                    b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.HasIndex("SaleNumber").IsUnique();
                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("SaleId").IsRequired().HasColumnType("uuid");
                    b.Property<Guid>("ProductId").IsRequired().HasColumnType("uuid");
                    b.Property<string>("ProductName").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<int>("Quantity").IsRequired().HasColumnType("integer");
                    b.Property<decimal>("UnitPrice").IsRequired().HasColumnType("numeric(18,2)");
                    b.Property<decimal>("Discount").IsRequired().HasColumnType("numeric(5,4)");
                    b.Property<decimal>("TotalAmount").IsRequired().HasColumnType("numeric(18,2)");
                    b.Property<bool>("IsCancelled").IsRequired().HasColumnType("boolean");

                    b.HasKey("Id");
                    b.HasIndex("SaleId");
                    b.ToTable("SaleItems", (string)null);

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
